### ISSUE TITLE
Target hardware

### ISSUE THREAD

**Issue by saturn77** [hdlguy/microblaze_command_processor#1]
Hello hdlguy; 

The microblaze_command_processor is targeted for the Avnet Artix-7 50 board, correct? I just wanted to confirm this. 

Thanks. James

**Comment by hdlguy** [comment]
Hello, Yes. Thanks for asking. I run it on the Avnet Artix-7 50 board.  I think it would be easy to run on any 7-Series board though.  Were you able to run it on your end?

  Pete
